<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="TIJO_PC" failures="4" tests="39" name="com.share.testscript.Home" time="965.601" errors="0" timestamp="2020-09-30T13:58:50 IST" skipped="0">
  <testcase classname="com.share.testscript.Home" name="TC_Home_001" time="22.895"/>
  <testcase classname="com.share.testscript.Home" name="TC_Home_002" time="23.083"/>
  <testcase classname="com.share.testscript.Home" name="TC_Home_003_005" time="48.677"/>
  <testcase classname="com.share.testscript.Home" name="TC_Home_053" time="20.761"/>
  <testcase classname="com.share.testscript.Home" name="TC_Home_004" time="27.740"/>
  <testcase classname="com.share.testscript.Home" name="TC_Home_006" time="5.206"/>
  <testcase classname="com.share.testscript.Home" name="TC_Home_007" time="3.379"/>
  <testcase classname="com.share.testscript.Home" name="TC_Home_008" time="20.662"/>
  <testcase classname="com.share.testscript.Home" name="TC_Home_009" time="12.096"/>
  <testcase classname="com.share.testscript.Home" name="TC_Home_010" time="9.207"/>
  <testcase classname="com.share.testscript.Home" name="TC_Home_011" time="4.105"/>
  <testcase classname="com.share.testscript.Home" name="TC_Home_012" time="4.159"/>
  <testcase classname="com.share.testscript.Home" name="TC_Home_013" time="5.528"/>
  <testcase classname="com.share.testscript.Home" name="TC_Home_014" time="7.055"/>
  <testcase classname="com.share.testscript.Home" name="TC_Home_015" time="13.144"/>
  <testcase classname="com.share.testscript.Home" name="TC_Home_016" time="14.528"/>
  <testcase classname="com.share.testscript.Home" name="TC_Home_056" time="2.765"/>
  <testcase classname="com.share.testscript.Home" name="TC_Home_064" time="3.821"/>
  <testcase classname="com.share.testscript.Home" name="TC_Home_017" time="2.845"/>
  <testcase classname="com.share.testscript.Home" name="TC_Home_065" time="1.138"/>
  <testcase classname="com.share.testscript.Home" name="TC_Home_067" time="5.665"/>
  <testcase classname="com.share.testscript.Home" name="TC_Home_080" time="4.796"/>
  <testcase classname="com.share.testscript.Home" name="TC_Home_068" time="1.182"/>
  <testcase classname="com.share.testscript.Home" name="TC_Home_070" time="26.476"/>
  <testcase classname="com.share.testscript.Home" name="TC_Home_071" time="106.363">
    <failure message="Error Occured" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Error Occured
at org.testng.Assert.fail(Assert.java:97)
at com.share.testscript.Home.TC_Home_071(Home.java:1384)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1507)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- TC_Home_071 -->
  <testcase classname="com.share.testscript.Home" name="TC_Home_072" time="36.087"/>
  <testcase classname="com.share.testscript.Home" name="TC_Home_073" time="89.638">
    <failure message="Error Occured" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Error Occured
at org.testng.Assert.fail(Assert.java:97)
at com.share.testscript.Home.TC_Home_073(Home.java:1474)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1507)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- TC_Home_073 -->
  <testcase classname="com.share.testscript.Home" name="TC_Home_074" time="27.892"/>
  <testcase classname="com.share.testscript.Home" name="TC_Home_028" time="78.605">
    <failure message="Error Occured" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Error Occured
at org.testng.Assert.fail(Assert.java:97)
at com.share.testscript.Home.TC_Home_028(Home.java:1567)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1507)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- TC_Home_028 -->
  <testcase classname="com.share.testscript.Home" name="TC_Home_029" time="7.645"/>
  <testcase classname="com.share.testscript.Home" name="TC_Home_030" time="4.721"/>
  <testcase classname="com.share.testscript.Home" name="TC_Home_041" time="25.976"/>
  <testcase classname="com.share.testscript.Home" name="TC_Home_042" time="131.672"/>
  <testcase classname="com.share.testscript.Home" name="TC_Home_043" time="70.261">
    <failure message="Error Occured" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Error Occured
at org.testng.Assert.fail(Assert.java:97)
at com.share.testscript.Home.TC_Home_043(Home.java:1780)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1507)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- TC_Home_043 -->
  <testcase classname="com.share.testscript.Home" name="TC_Home_N053" time="24.685"/>
  <testcase classname="com.share.testscript.Home" name="TC_Home_058_059_60_61_62" time="8.828"/>
  <testcase classname="com.share.testscript.Home" name="TC_Home_N063" time="6.662"/>
  <testcase classname="com.share.testscript.Home" name="TC_Home_N064" time="3.672"/>
  <testcase classname="com.share.testscript.Home" name="TC_Home_SO001" time="51.981"/>
</testsuite> <!-- com.share.testscript.Home -->
