<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="THSLT10138" ignored="0" name="Test2" tests="4" failures="0" timestamp="2020-07-13T17:34:50 IST" time="35.393" errors="0">
  <testcase name="@BeforeTest createAndroidDriver" time="34.617" classname="com.share.general.DriverSetUp">
    <failure type="org.openqa.selenium.SessionNotCreatedException" message="Unable to create a new remote session. Please check the server log for more details. Original error: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: &amp;apos;Command &amp;apos;D\:\\AppData\\platform-tools\\adb.exe -P 5037 -s 192.168.94.102\:5555 forward tcp\:8200 tcp\:6790&amp;apos; exited with code 1&amp;apos;; Stderr: &amp;apos;adb.exe: error: more than one device/emulator&amp;apos;; Code: &amp;apos;1&amp;apos;
Build info: version: &amp;apos;3.141.59&amp;apos;, revision: &amp;apos;e82be7d358&amp;apos;, time: &amp;apos;2018-11-14T08:17:03&amp;apos;
System info: host: &amp;apos;THSLT10138&amp;apos;, ip: &amp;apos;192.168.94.2&amp;apos;, os.name: &amp;apos;Windows 10&amp;apos;, os.arch: &amp;apos;amd64&amp;apos;, os.version: &amp;apos;10.0&amp;apos;, java.version: &amp;apos;1.8.0_162&amp;apos;
Driver info: driver.version: AndroidDriver
remote stacktrace: UnknownError: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: &amp;apos;Command &amp;apos;D\:\\AppData\\platform-tools\\adb.exe -P 5037 -s 192.168.94.102\:5555 forward tcp\:8200 tcp\:6790&amp;apos; exited with code 1&amp;apos;; Stderr: &amp;apos;adb.exe: error: more than one device/emulator&amp;apos;; Code: &amp;apos;1&amp;apos;
    at getResponseForW3CError (C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\protocol\errors.js:826:9)
    at asyncHandler (C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\protocol\protocol.js:447:37)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Build info: version: &amp;apos;3.141.59&amp;apos;, revision: &amp;apos;e82be7d358&amp;apos;, time: &amp;apos;2018-11-14T08:17:03&amp;apos;
System info: host: &amp;apos;THSLT10138&amp;apos;, ip: &amp;apos;192.168.94.2&amp;apos;, os.name: &amp;apos;Windows 10&amp;apos;, os.arch: &amp;apos;amd64&amp;apos;, os.version: &amp;apos;10.0&amp;apos;, java.version: &amp;apos;1.8.0_162&amp;apos;
Driver info: driver.version: AndroidDriver">
      <![CDATA[org.openqa.selenium.SessionNotCreatedException: Unable to create a new remote session. Please check the server log for more details. Original error: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command 'D\:\\AppData\\platform-tools\\adb.exe -P 5037 -s 192.168.94.102\:5555 forward tcp\:8200 tcp\:6790' exited with code 1'; Stderr: 'adb.exe: error: more than one device/emulator'; Code: '1'
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'THSLT10138', ip: '192.168.94.2', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_162'
Driver info: driver.version: AndroidDriver
remote stacktrace: UnknownError: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command 'D\:\\AppData\\platform-tools\\adb.exe -P 5037 -s 192.168.94.102\:5555 forward tcp\:8200 tcp\:6790' exited with code 1'; Stderr: 'adb.exe: error: more than one device/emulator'; Code: '1'
    at getResponseForW3CError (C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\protocol\errors.js:826:9)
    at asyncHandler (C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\protocol\protocol.js:447:37)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'THSLT10138', ip: '192.168.94.2', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_162'
Driver info: driver.version: AndroidDriver
at io.appium.java_client.remote.AppiumCommandExecutor$1.createSession(AppiumCommandExecutor.java:208)
at io.appium.java_client.remote.AppiumCommandExecutor.createSession(AppiumCommandExecutor.java:217)
at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:239)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:41)
at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
at io.appium.java_client.android.AndroidDriver.execute(AndroidDriver.java:1)
at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:213)
at io.appium.java_client.AppiumDriver.startSession(AppiumDriver.java:323)
at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:131)
at io.appium.java_client.DefaultGenericMobileDriver.<init>(DefaultGenericMobileDriver.java:37)
at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:86)
at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:96)
at io.appium.java_client.android.AndroidDriver.<init>(AndroidDriver.java:94)
at com.share.general.DriverSetUp.createAndroidDriver(DriverSetUp.java:178)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
at io.appium.java_client.remote.AppiumCommandExecutor$1.createSession(AppiumCommandExecutor.java:186)
... 33 more
Caused by: org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command 'D\:\\AppData\\platform-tools\\adb.exe -P 5037 -s 192.168.94.102\:5555 forward tcp\:8200 tcp\:6790' exited with code 1'; Stderr: 'adb.exe: error: more than one device/emulator'; Code: '1'
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'THSLT10138', ip: '192.168.94.2', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_162'
Driver info: driver.version: AndroidDriver
remote stacktrace: UnknownError: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command 'D\:\\AppData\\platform-tools\\adb.exe -P 5037 -s 192.168.94.102\:5555 forward tcp\:8200 tcp\:6790' exited with code 1'; Stderr: 'adb.exe: error: more than one device/emulator'; Code: '1'
    at getResponseForW3CError (C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\protocol\errors.js:826:9)
    at asyncHandler (C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\protocol\protocol.js:447:37)
    at process._tickCallback (internal/process/next_tick.js:68:7)
at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$errorHandler$0(W3CHandshakeResponse.java:62)
at org.openqa.selenium.remote.HandshakeResponse.lambda$getResponseFunction$0(HandshakeResponse.java:30)
at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$0(ProtocolHandshake.java:126)
at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
at java.util.Spliterators$ArraySpliterator.tryAdvance(Unknown Source)
at java.util.stream.ReferencePipeline.forEachWithCancel(Unknown Source)
at java.util.stream.AbstractPipeline.copyIntoWithCancel(Unknown Source)
at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
at java.util.stream.FindOps$FindOp.evaluateSequential(Unknown Source)
at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
at java.util.stream.ReferencePipeline.findFirst(Unknown Source)
at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:128)
... 38 more
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- @BeforeTest createAndroidDriver -->
  <testcase name="@AfterMethod setTestResult" time="0.001" classname="com.share.general.DriverSetUp">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com.share.general.DriverSetUp.setTestResult(DriverSetUp.java:185)
at java.util.ArrayList.forEach(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 23 stack frames]]>
    </failure>
  </testcase> <!-- @AfterMethod setTestResult -->
  <testcase name="@AfterMethod setTestResult" time="0.001" classname="com.share.general.DriverSetUp">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com.share.general.DriverSetUp.setTestResult(DriverSetUp.java:185)
at java.util.ArrayList.forEach(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 23 stack frames]]>
    </failure>
  </testcase> <!-- @AfterMethod setTestResult -->
  <testcase name="TC_SignIn_001_007" time="0.0" classname="com.share.testscript.SignIn">
    <skipped/>
  </testcase> <!-- TC_SignIn_001_007 -->
  <testcase name="TC_SignIn_001_007" time="0.0" classname="com.share.testscript.SignIn">
    <skipped/>
  </testcase> <!-- TC_SignIn_001_007 -->
  <testcase name="TC_SignIn_015" time="0.0" classname="com.share.testscript.SignIn">
    <skipped/>
  </testcase> <!-- TC_SignIn_015 -->
  <testcase name="TC_SignIn_015" time="0.0" classname="com.share.testscript.SignIn">
    <skipped/>
  </testcase> <!-- TC_SignIn_015 -->
</testsuite> <!-- Test2 -->
